[package]
name = "circetz"
version = "0.1.0"
compiler = "0.13.0"
entrypoint = "src/exports.typ"
authors = ["Louis Grange"]
license = "MIT"
description = "A package to draw amazing electronic circuits using CeTZ"
repository = "https://github.com/l0uisgrange/circetz"
categories = ["visualization", "components"]
keywords = ["electronic", "circuit", "cetz", "voltage", "draw", "schema", "engineering"]