name: 🐞 Bug Report
description: Report a problem or error
labels: ["bug"]
assignees:
  - l0uisgrange
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the bug.
      placeholder: Describe the bug here...
    validations:
      required: true
  - type: dropdown
    id: package_version
    attributes:
      label: Zap Version
      description: The version of Zap you are using.
      options:
        - Development
        - 0.3.0 (default)
        - 0.2.1
        - 0.2.0
        - 0.1.0
        - Other
      default: 1
    validations:
      required: true
  - type: dropdown
    id: typst_compiler_version
    attributes:
      label: Typst Version
      description: Select the Typst version you are using.
      options:
        - Development
        - 0.13.1 (default)
        - 0.13.0
        - 0.12.0
        - 0.11.1
        - 0.11.0
        - 0.10.0
        - Other
      default: 1
    validations:
      required: true
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Screenshots, error messages, etc.
    validations:
      required: false
