name: Feature Request
description: Propose a new feature for the package.
title: "[Feature]: "
labels: ["enhancement"]
assignees:
  - l0uisgrange
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Clearly explain the feature you are requesting.
      placeholder: Describe what the feature is and how it would improve the package.
    validations:
      required: true
  - type: textarea
    id: usecase
    attributes:
      label: Use Case
      description: How would you or others use this feature?
      placeholder: Describe typical usage scenarios.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative approaches?
      placeholder: List alternative solutions or explain why none exist.
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context or mockups about the feature request.
      placeholder: Sketches, references, related issues, etc.
    validations:
      required: false
