name: ⚡️ Component Suggestion
description: Suggest a new or modified electronic component for the package.
title: "[Component]: "
labels: ["enhancement", "component"]
assignees:
  - l0uisgrange
body:
  - type: textarea
    id: name
    attributes:
      label: Declaration Example
      description: How would your component be declared? Needs additional options?
      value:
        ```typst 
        mycomponent("id", (x, y), ...your-params)
        ```
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References or Images
      description: What does the component look like?
      placeholder: Links, datasheets, sketches, etc.
    validations:
      required: true