name: Component Suggestion
description: Suggest a new or modified electronic component for the package.
title: "[Component]: "
labels: ["enhancement", "component"]
assignees:
  - l0uisgrange
body:
  - type: input
    id: name
    attributes:
      label: Component Name
      description: What is the name of the component you suggest?
      placeholder: e.g., Op-Amp, MOSFET, Transformer
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the component and why it should be added.
      placeholder: Explain its purpose, typical use, and key characteristics.
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References or Images
      description: Provide references, datasheets, or example diagrams if available.
      placeholder: Links, datasheets, sketches, etc.
    validations:
      required: false