name: ⚡️ Component Suggestion
description: Suggest a new or modified electronic component for the package.
title: "[Component]: "
labels: ["enhancement", "component"]
assignees:
  - l0uisgrange
body:
  - type: input
    id: name
    attributes:
      label: Component Name
      description: What is the name of the component you suggest?
      placeholder: e.g., Op-Amp, MOSFET, Transformer
    validations:
      required: true
  - type: textarea
    id: references
    attributes:
      label: References or Images
      description: What does the component look like?
      placeholder: Links, datasheets, sketches, etc.
    validations:
      required: true