// All components
// wire, node, capacitor, diode, led, photodiode, schottky, tunnel, zener, opamp, switch, afuse, fuse, earth, frame, ground, vcc, vee, inductor, heater, potentiometer, resistor, rheostat, vsource, dvsource, acvsource, isource, disource, acisource, acmotor, dcmotor, bjt, npn, pnp, mosfet, nmos, nmosd, pmos, pmosd

#let default = (
    style: (
        variant: "iec",
        scale: (x: 1.0, y: 1.0),
        stroke: (
            thickness: 0.021,
            paint: black,
        ),
        label: (
            variant: auto,
            scale: auto,
            content: none,
            distance: 7pt,
            anchor: "north",
            tolerance: 15,
        ),
        pin: (
            variant: auto,
            stroke: auto,
            length: 24pt,
        ),
        node: (
            radius: .04,
            stroke: auto,
            fill: auto,
            nofill: white,
        ),
        wire: (
            variant: auto,
            stroke: auto,
            lbind: true
        ),
        arrow: (
            variant: "default",
            length: 1,
            angle: 60deg,
            ratio: (0.5, 0.4),
            stroke: (
               thickness: 0.8pt,
               paint: black,
            ),
        ),
        debug: (
            radius: .7pt,
            stroke: (
                thickness: .2pt,
                paint: red
            ),
            angle: -30deg,
            shift: 3pt,
            font: 3pt,
            fill: red,
        ),

        // Components
        capacitor: (
            variant: auto,
            scale: auto,
            stroke: auto,
            width: .8,
            distance: .25,
        ),
        diode: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .3,
            line: .25,
            tunnel-length: .1,
        ),
        led: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .3,
            line: .25,
            tunnel-length: .1,
        ),
        photodiode: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .3,
            line: .25,
            tunnel-length: .1,
        ),
        schottky: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .3,
            line: .25,
            tunnel-length: .1,
        ),
        tunnel: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .3,
            line: .25,
            tunnel-length: .1,
        ),
        zener: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .3,
            line: .25,
            tunnel-length: .1,
        ),
        opamp: (
            variant: auto,
            scale: auto,
            stroke: auto,
            width: 1.8,
            height: 1.75,
            padding: .28,
            sign-stroke: .55pt,
            sign-size: .14,
            sign-delta: .45,
        ),
        switch: (
            variant: auto,
            scale: auto,
            stroke: auto,
            width: .8,
            angle: 35deg,
        ),
        afuse: (
            variant: auto,
            scale: auto,
            stroke: auto,
            width: .88,
            height: .88 / 2.4,
            asymmetry: 25%,
        ),
        fuse: (
            variant: auto,
            scale: auto,
            stroke: auto,
            width: .88,
            height: .88 / 2.4,
            asymmetry: 25%,
        ),
        ground: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: 0.03,
                paint: auto,
            ),
            envelope-radius: 0.4,
            radius: 0.26,
            distance: 0.6,
            number: 3,
            width: 0.56,
            stepv: 0.1,
            steph: 0.16,
            chassis: (
                width: 0.6,
                angle: 20deg,
                depth: 0.25,
            ),
        ),
        vcc: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: 0.04,
                paint: auto,
            ),
            angle: 35deg,
            radius: .4,
            distance: .6,
        ),
        vee: (
            variant: auto,
            scale: auto,
            stroke: (
                thickness: 0.04,
                paint: auto,
            ),
            label: (
                anchor: "south",
            ),
            angle: 35deg,
            radius: .4,
            distance: .6,
        ),
        inductor: (
            variant: auto,
            scale: auto,
            stroke: auto,
            width: 1.41,
            height: 1.41 / 3,
            bumps: 4,
            extra: 0.01,
            fall: "zap-auto",
            latex: (
                height: 0.6,
                width: 1.3,
                bumps: 5,
                stroke: (
                    thickness: 0.04,
                ),
            ),
        ),
        heater: (
            variant: auto,
            scale: auto,
            stroke: auto,
            width: 1.41,
            height: .47,
            zigs: 3,
            shift: 0.22pt,
        ),
        potentiometer: (
            variant: auto,
            scale: auto,
            stroke: auto,
            width: 1.41,
            height: .47,
            zigs: 3,
            shift: 0.22pt,
        ),
        resistor: (
            variant: auto,
            scale: auto,
            stroke: auto,
            width: 1.41,
            height: .47,
            zigs: 3,
            extra: 0.001,
            latex: (
                stroke: (
                    thickness: 0.034,
                ),
            ),
        ),
        rheostat: (
            variant: auto,
            scale: auto,
            stroke: auto,
            width: 1.41,
            height: .47,
            zigs: 3,
            shift: 0.22pt,
        ),
        vsource: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .53,
            padding: .25,
            sign-stroke: .55pt,
            sign-size: .14,
            sign-delta: .07,
        ),
        dvsource: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .53,
            padding: .25,
            sign-stroke: .55pt,
            sign-size: .14,
            sign-delta: .07,
        ),
        acvsource: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .53,
            padding: .25,
            sign-stroke: .55pt,
            sign-size: .14,
            sign-delta: .07,
        ),
        isource: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .53,
            padding: .25,
            arrow-scale: 3,
        ),
        disource: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .53,
            padding: .25,
            arrow-scale: 3,
        ),
        acisource: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .53,
            padding: .25,
            arrow-scale: 3,
        ),
        acmotor: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .49,
            magnet-width: 1.23,
            magnet-height: 1.23 / 4,
        ),
        dcmotor: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .49,
            magnet-width: 1.23,
            magnet-height: 1.23 / 4,
        ),
        bjt: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .65,
            base-height: .6,
            base-distance: .12,
            aperture: 50deg,
        ),
        npn: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .65,
            base-height: .6,
            base-distance: .12,
            aperture: 50deg,
        ),
        pnp: (
            variant: auto,
            scale: auto,
            stroke: auto,
            radius: .65,
            base-height: .6,
            base-distance: .12,
            aperture: 50deg,
        ),
        mosfet: (
            variant: auto,
            scale: auto,
            stroke: auto,
            height: 0.795,
            width: 1.065,
            base-width: 1.35,
            base-spacing: 0.165,
            base-distance: 0.165,
            radius: 1.05,
        ),
        nmos: (
            variant: auto,
            scale: auto,
            stroke: auto,
            height: 0.795,
            width: 1.065,
            base-width: 1.35,
            base-spacing: 0.165,
            base-distance: 0.165,
            radius: 1.05,
        ),
        nmosd: (
            variant: auto,
            scale: auto,
            stroke: auto,
            height: 0.795,
            width: 1.065,
            base-width: 1.35,
            base-spacing: 0.165,
            base-distance: 0.165,
            radius: 1.05,
        ),
        pmos: (
            variant: auto,
            scale: auto,
            stroke: auto,
            height: 0.795,
            width: 1.065,
            base-width: 1.35,
            base-spacing: 0.165,
            base-distance: 0.165,
            radius: 1.05,
        ),
        pmosd: (
            variant: auto,
            scale: auto,
            stroke: auto,
            height: 0.795,
            width: 1.065,
            base-width: 1.35,
            base-spacing: 0.165,
            base-distance: 0.165,
            radius: 1.05,
        ),
    ),
    params: (
        debug: false
    )
)
