name: CI
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:
jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Typst
        run: sudo snap install typst
      - name: Install Tytanic
        uses: taiki-e/cache-cargo-install-action@v2
        with:
          tool: tytanic@0.2.2
      - name: Run test suite
        run: tt run --no-fail-fast
      - name: Archive artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: artifacts
          path: |
            tests/**/diff/*.png
            tests/**/out/*.png
            tests/**/ref/*.png
          retention-days: 3